sudo: enabled
language: cpp

compiler: gcc

install:
  - mkdir NewCMake
  - cd NewCmake
  - sudo apt remove cmake
  - wget "https://cmake.org/files/v3.10/cmake-3.10.0-rc5.tar.gz"
  - cd cmake-3.10.0-rc5
  - sudo apt-get install autoconf # for ./configure
  - ./configure
  - make
  - make install
script:
  - cmake CMakeLists.txt
  - make
  - ./FontController
