sudo: require  # be a sudo

git:
  depth: 1

language: cpp

compiler: gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - sudo apt-get install qtbase5-dev

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 4 # give xvfb some time to start

script:
  - cmake CMakeLists.txt
  - make
  - ./FontController
